# Generated by Django 3.0.8 on 2020-07-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend_money_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(upload_to='product_img/'),
        ),
    ]
